const MOVIES_URL = "https://api.nomoreparties.co/beatfilm-movies"
const MAIN_URL = "https://api.oleestral.diploma.nomoredomains.rocks"
const CONTENT_URL = "https://api.nomoreparties.co"
const SHORT_MOVIE_DURATION = 40
const MOVIES_NUMBER_SMALL_SCREEN = 5
const MOVIES_NUMBER_SMALL_SCREEN_ADD = 1
const MOVIES_NUMBER_MEDUIM_SCREEN = 8
const MOVIES_NUMBER_MEDIUM_SCREEN_ADD = 2
const MOVIES_NUMBER_BIG_SCREEN = 12
const MOVIES_NUMBER_BIG_SCREEN_ADD = 5

export {MAIN_URL, MOVIES_URL, CONTENT_URL, SHORT_MOVIE_DURATION, 
    MOVIES_NUMBER_SMALL_SCREEN, MOVIES_NUMBER_SMALL_SCREEN_ADD, 
    MOVIES_NUMBER_MEDUIM_SCREEN,MOVIES_NUMBER_MEDIUM_SCREEN_ADD,
    MOVIES_NUMBER_BIG_SCREEN, MOVIES_NUMBER_BIG_SCREEN_ADD
}